- frontend/Dockerfile
- frontend/pubspec.lock
> [Feat/#1] Dockerfile 작성

- frontend/lib/screens/home_screen.dart
- frontend/pubspec.lock
#11 
- 메뉴 아이콘 이름 변경
전체대회 -> 경진대회
기타 -> 팀원모집으로 변경
> [fix : #11] 홈 화면 UI 수정

- frontend/lib/screens/board_screen.dart
- frontend/lib/screens/hiddenList_screen.dart
- frontend/lib/widgets/board_widget.dart
- frontend/lib/widgets/levelBtn_widget.dart
- frontend/pubspec.lock
#17
-  숨김 버튼을 눌렀을 때, 해당 학년의 리스트에서 체크된 게시글을 hiddenList로 이동
- 숨김을 한 게시글을 숨김 목록 페이지에서 시연
- hiddenList를 BoardPage에서 가져와 ListView.builder 메서드로 구현
- 숨김해제 시 selectedHiddenItems에 추가해  removewhere 메서드로 숨김 목록 화면에 제거 구현
- hiddenList에 제거
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/05f50001-9385-47d6-a5c0-9cbad419896f
onInsert, addAll, removeWhere, where 메서드
> [Feat/#17] 숨김 목록 페이지 구현 및 숨김 해제 기능 구현

- frontend/lib/screens/userInfo_screen.dart
#23
- ListTile 위젯으로 공통 위젯으로 만든 뒤 title, info에 상황에 맞게 삽입
> [Feat/#23] 마이페이지 회원정보 화면 구현

- frontend/lib/screens/login_screen.dart
- frontend/pubspec.lock
#39
- SizedBox 위젯을 제거하고 contentPadding 추가
> [Fix/#39] 로그인 아이디 수정

- frontend/ios/Podfile.lock
- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/lib/screens/viewVote_screen.dart
- frontend/lib/screens/vote_screen.dart
- frontend/pubspec.yaml
#48 
- Spacer를 사용하여 컨테이너에서 간격 조절할 수 있도록 설정
> [feat : #48] 항목별 조회 페이지 구현

- frontend/lib/screens/board_screen.dart
- frontend/lib/screens/favorite_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/widgets/board_widget.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
#55
- 상단바에 좋아요 아이콘 추가
- 좋아요 아이콘에 좋아요 페이지 이동 기능 구현
- isLiked 키값을 주어 눌렀을 때 빨간색으로 채워지는 favorite 아이콘으로 변환
- count 키값을 주어 isLiked이 true일 경우 count값 1 증가, false일 경우 count 값 1 감소
- 선택 버튼 누를 시 취소와 삭제 버튼 생성
- 삭제 버튼을 누를 시 where를 사용하여 isDeleted가 true일 경우 favoriteList에 제거 기능 구현
- 좋아요 개수 1 감소와 choseBtn을 false로 변환
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/d0b6715b-8ad8-4260-9084-806a157ed4b1
where 메서드
> [Feat/#55] 좋아요 페이지 구현

- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/lib/main.dart
- frontend/lib/screens/contestTeamList_screen.dart
- frontend/lib/screens/experience_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/screens/teamRecruitList_screen.dart
- frontend/lib/screens/write_screen.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
> [Feat/#66] 프로젝트 경험 페이지 구현

- frontend/lib/screens/write_screen.dart
#68
- 이미지 버튼으로 변경
- 누르면 bottomsheet로 카메라와 갤러리 버튼 구현
- 선택한 파일의 파일명 보이게 구현
- 이미지 삭제 버튼 위치 수정
- onPressed 속성 안의 코드는 함수로 분리
- 공통 위젯들은 위젯함수로 분리
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/ab1d6ccb-22d2-41a8-982d-2e78af1142d3
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/cbc48124-790f-4fb1-9367-6d574d9dc6b3
> [Fix/#68] 작성 페이지에서 ImagePicker 코드 수정

- frontend/lib/widgets/levelBtn_widget.dart
> [fix : #74] 학년 공지에서 학년 버튼 디자인 수정

- frontend/ios/Podfile.lock
- frontend/lib/admin/models/admin_model.dart
- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/addMember_screen.dart
- frontend/lib/admin/screens/userInfo_screen.dart
- frontend/lib/admin/services/userInfo_service.dart
- frontend/lib/main.dart
- frontend/macos/Flutter/GeneratedPluginRegistrant.swift
- frontend/pubspec.lock
- frontend/pubspec.yaml
#79 
- Multipart롤 활용해서 파일을 서버로 전송
- 선택한 파일 내용을 바이트 배열로 읽어온 후 fromBytes 메서드를 활용해서 전송
- Json 맵 형식으로 변환
- Admin 객체를 문자열 형식으로 표현해서 화면에 표시할 때 사용
- 엑셀로 member 업데이트 API에서 List를 반환
- 회원정보리스트 admins에 저장해 Provider로 상태 관리
-선택한 파일은 shared_preference를 활용해서 저장
- FutureBuilder 위젯을 사용해서 Datatable에 회원정보를 화면에 표시
Provider, shared_preference 
https://totally-developer.tistory.com/83
> [Feat(admin)/#79] 엑셀로 member 업데이트 API 연동

- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/userInfo_screen.dart
- frontend/lib/admin/services/userInfo_service.dart
#83
- userList를 초기화해 엑셀로 member 업데이트 api 연동하면 setState로 userList 상태값 변경
- consumer 위젯을 사용해 일부부분만 rebuild 될 수 있도록 구현
> [Feat(admin)/#83] member 전체 조회 API 연동

- frontend/ios/Podfile.lock
- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/lib/screens/login_screen.dart
- frontend/lib/services/login_services.dart
- frontend/macos/Flutter/GeneratedPluginRegistrant.swift
- frontend/pubspec.lock
- frontend/pubspec.yaml
#76 
- services 폴더 추가
- API 연동 코드는 따로 분리
- 페이지 이동을 직접 Navigator 형식으로 접근하지 않고 자동 로그인 시 페이지 이동 함수 적용하여 true / false로 관리
> [Feat/#76] 로그인 API 연동 & 토큰 재발급 API 연동

- frontend/lib/admin/models/admin_model.dart
- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/userInfo_screen.dart
- frontend/lib/admin/services/userInfo_service.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
#87
회원 정보 수정 API 연동
- admin 모델에서 변경으로 인해 final 삭제
- 이름과 학번은 onChanged 속성을 사용해 값 업데이트
- 학년은 true가 되는 index를 가져온 후 1을 더해서 값 업데이트
- 학번은 firstWhere를 사용해 value값에 맞는 첫번째 요소를 찾아 해당하는 값, title를 가져와 값 업데이트
- admins의 학번과 admin 학번과 동일한 요소의 index를 가져와 수정된 admin을 admins 리스트에 저장해 수정
https://github.com/user-attachments/assets/1ed47e74-e0bc-48b7-ac80-ae421216e609
indexWhere
> [Feat(admin)/#87] member 정보 수정

- frontend/ios/Podfile.lock
- frontend/lib/main.dart
- frontend/lib/models/makeTeam_modal.dart
- frontend/lib/providers/makeTeam_provider.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/services/makeTeam_service.dart
- frontend/linux/flutter/generated_plugin_registrant.cc
- frontend/linux/flutter/generated_plugins.cmake
- frontend/macos/Flutter/GeneratedPluginRegistrant.swift
- frontend/pubspec.lock
- frontend/pubspec.yaml
- frontend/windows/flutter/generated_plugin_registrant.cc
- frontend/windows/flutter/generated_plugins.cmake
#104 
[main]
- MakeTeamProvider 적용
[model]
- recruitmentStatus 필드 타입 bool로 변경
- service 파일 생성
- provider 파일 생성
[MakeTeamPage]
- 작성 완료 버튼 클릭할 시 model 안의 필드 기반으로 각각의 컨드롤러 적용
- 공지글 작성 API 완료 후 공지글 ID 추출 후 집어넣기
> [Feat/#104] 팀원 모집글 작성 API 연동

- frontend/lib/screens/home_screen.dart
#82 
- 회원정보들의 boolean을 모아둔 리스트를 만들어 userListData의 길이와 동일하게 설정한 후 false로 초기화
- 체크박스에 의해 선택된 회원정보의 학생 아이디를 가져와 selectedStudentIds에 추가
- 선택된 학생 아이디를 담은 리스트를 deleteMembers 메소드로 전달해 api 실행
- context.mounted를 사용하여 BuildContext 를 안전하게 참조할 수 있게 작성
- 검색했을 때 나오는 명단 리스트를 선언
- searchController.text를 사용해서 없으면 기존 userList를 가져오고 있으면 where 메소드를 사용
- Futurebuilder에서 검색어가 있을 경우 fliteredUserList 출력, 없으면 userList 출력되게 구현
- selectAll를 value로 설정해 userListData를 반복해 다 true로 설정
- 선택된 아이디에 학번 추가
> [Fix(admin)/#82] 너비 간격 조절

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/main.dart
- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/widgets/board_widget.dart
#114
- 경진대회 공지 페이지를 따로 분리
- categoryList를 provider에서 만들어 get 메소드를 통해 ListView.builder에서 사용
> [Feat/#114] 경진대회 카테고리 조회 API 연동

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/main.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/corSeaBoard_screen.dart
- frontend/lib/screens/gradeBoard_screen.dart
- frontend/lib/screens/hiddenList_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/widgets/board_widget.dart
#128
- 숨김 관리 팝업 메뉴에 숨김 페이지 이동 코드 작성
- initState에 숨김 목록 조회 API 호출
> [Feat/#128] 숨김 목록 조회 API 연동

- frontend/lib/models/vote_model.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/screens/write_screen.dart
#134
- 게시글 아이디를 받기 위해 게시글 작성 호출 뒤 투표 생성 API 호출
- 투표 항목 추가 위젯을 제거하고 복수선택 허용 체크박스와 종료일 설정을 묶어 설정 제목을 달아서 작성
> [Feat/#134] 투표 생성 API 연동

- frontend/lib/main.dart
- frontend/lib/models/teamApply_model.dart
- frontend/lib/providers/makeTeam_provider.dart
- frontend/lib/providers/teamApply_provider.dart
- frontend/lib/screens/memberRecruit_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/makeTeam_service.dart
- frontend/lib/services/teamApply_service.dart
> [feat : # 138] 팀원신청글 작성 API 연동

- frontend/lib/providers/vote_provider.dart
- frontend/lib/widgets/vote_widget.dart
> [Feat/#142] 투표 항목 추가(사용자) API 연동

- frontend/lib/main.dart
- frontend/lib/providers/recommend_provider.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/settingProfile2_screen.dart
#145
- 추천 API를 boolean 값으로 반환해 true일 경우 isLiked 불리안 값 변경과 likeCount 값 1증가 작업 실행
> [Feat/#145] 추천 API 연동

- frontend/lib/main.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/settingProfile2_screen.dart
- frontend/lib/screens/write_screen.dart
- frontend/lib/widgets/vote_widget.dart
- frontend/macos/Podfile.lock
- frontend/macos/Runner.xcodeproj/project.pbxproj
- frontend/macos/Runner.xcworkspace/contents.xcworkspacedata
#144
- 중복 투표 시 다음 투표 항목이 투표안되는 거 수정할 예정
- 투표 항목 아이디를 리스트로 담아 중복일 경우 리스트로 두번 호출하게 설정
- repetition을 받아 중복 투표 여부 설정
- 작성자는 투표 항목 추가와 투표하지 못하게 설정(snackbar로 알림)
> [Feat/#144] 투표하기 API 연동

- frontend/lib/models/teamApply_model.dart
- frontend/lib/providers/teamApply_provider.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/teamApply_service.dart
#152 
[model]
- id 선택적 필드로 추가
-- 팀원 신청글 id에 따라 수정되도록 코드 구현
-- 현재 사용자가 댓글 작성자인 경우에만 팝업 메뉴를 보여주도록 코드 구현
> [Feat/#152] 팀원 신청글 수정 API 연동

- frontend/lib/widgets/vote_widget.dart
#158
- Duration을 사용해서 종료 시간이 되면 투표 종료 API 호출 후 voteEnded를 true로 설정되게 작성
https://github.com/user-attachments/assets/f1ca30c5-a1f5-4cb2-8f8d-94e04ed4dcb1
> [Feat/#158] 투표 종료 시간 지나면 투표 종료 API 호출

- frontend/lib/main.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/services/profile_service.dart
- frontend/pubspec.lock
#160
- 이미지와 파일 초기화 메서드를 만들어 initstate에 선언
- 이미지와 파일을 받아 디코딩해서 출력
> [Feat/#160] 게시글 이미지와 파일 조회 API 연동

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/providers/makeTeam_provider.dart
- frontend/lib/providers/teamApply_provider.dart
- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/screens/memberRecruit_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/makeTeam_service.dart
- frontend/lib/services/teamApply_service.dart
#156
- 팀원 모집글 공지글 아이디로 조회 시 acceptMemberList 추출되도록 코드 구현
- 팀원 모집글 조회 시 acceptMemberList 추출되도록 코드 구현
- MemberRecruitPage & RecruitDetailPage 각각 acceptMemberList.length 비교하여 인원 수가 적용되도록 코드 구현
- 현재 사용자가 댓글 작성자인 경우에만 팝업 메뉴를 보여 줌
- service 작성
- provider 작성
> [Feat/#156] 팀원 신청글 수락,거절 API 연동

- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/contestTeamList_screen.dart
#169 
- selectedCategory를 받아서 경진대회가 아닐 경우 메서드 호출되게 구현
> [Feat/#169] Team 카테고리별 삭제 API 연동

- frontend/lib/main.dart
- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/corSeaBoard_screen.dart
- frontend/lib/screens/gradeBoard_screen.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/screens/memberRecruit_screen.dart
- frontend/lib/screens/myOwnerPage_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/screens/setExperience_screen.dart
- frontend/lib/screens/setProfile_screen.dart
- frontend/lib/screens/setSkill_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/screens/write_screen.dart
- frontend/lib/widgets/position_list.dart
#179
- field와 tool 리스트를 외부 파일로 분리
- 파일명 변경(프로필 설정 -> setProfile, 경험 설정 -> setExperience, 기술 설정 -> setSkill)
- 선택한 공지 버튼 내용에 맞게 경진대회 카테고리를 잘 전달할 수 있도록 수정
- 투표 확인 버튼 누를 시 색상 바로 푸르러지게 수정
- 경진대회 공지에서 카테고리 제거
- cateBoardList에서 cate와 _parseCategoryName(cateBoard['announcementTitle'])이 동일한 첫 번째 항목을 확인
- 찾은 항목(match)에서 id 값을 추출
- 여러 줄을 작성해야 할 때 줄바꿈 가능한 키보드(TextInputType.multiline)로 바꾸고
- 확인 버튼이 있는 키보드로 추가(TextInputAction.done)
- 게시글마다 수정/삭제 크기 수정
-  프로필 페이지에서 프로필 아이콘 제거 및 사용자 페이지에서 계정 부분 밑으로 고정
- 작성하기에서 나갈 때 원래 왔던 경진대회 공지로 돌아가기
> [Fix/#179] 안되거나 부족한 기능 수정하기

- frontend/lib/providers/makeTeam_provider.dart
- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/screens/memberRecruit_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/makeTeam_service.dart
#184 
- announcementId selectItem에 따라 다르게 적용되도록 코드 수정
- 모집글 수정 / 삭제 팝업 메뉴로 관리
- 팀원 모집글 작성 시 작성완료, 수정 시 수정 완료 텍스트 적용
- 삭제 클릭 시 UI에도 즉시 적용되도록 코드 구현
- service 작성
- provider 작성
> [Feat/#184] 팀원 모집글 삭제 api 연동

- frontend/lib/providers/profile_provider.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
#191
- 생성된 팀 없을 때 null 오류 해결
- 글쓴 사람 & 신청자 기술 스택 조회되도록 코드 구현
- 팀 생성 완료 하면 팀 생성하기 버튼 -> 모집 완료 버튼으로 변경 & 모집 완료 시 댓글 창 닫음
> [feat : #191] 글쓴 사람 & 신청자 기술 스택 조회 안 되는 오류 해결

- frontend/lib/providers/announcement_provider.dart
- frontend/lib/providers/file_provider.dart
- frontend/lib/providers/recommend_provider.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/services/login_services.dart
- frontend/lib/services/makeTeam_service.dart
- frontend/lib/services/notification_services.dart
- frontend/lib/services/profile_service.dart
- frontend/lib/services/projectExperience_service.dart
- frontend/lib/services/teamApply_service.dart
> [Refactor/#197] 엔드포인트를 원격 서버용으로 교체

- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
#216 
[마이유저]
- Expanded 위젯을 사용하여 프로필과 기술 스택이 화면에서 적절한 공간을 차지하도록 조정
[로그인]
- resizeToAvoidBottomInset: true로 설정하여 키보드가 올라올 때 화면을 자동으로 조정하도록
- 키보드가 화면을 가릴 경우 스크롤을 통해 컨텐츠를 볼 수 있도록 설정
- 로그인 페이지 배경색 white로 수정
> [Fix/#216] 안드로이드 실제 기기에서 MyUserPage 오버플로우 오류 수정

- frontend/lib/screens/privacyPolicy_screen.dart
- frontend/lib/widgets/account_widget.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
#222
- 계정 위젯 부분에 개인정보처리방침 추가
- privacyPolicyPage 추가
> [feat : #222] 개인정보처리방침 추가하기

- frontend/lib/widgets/account_widget.dart
#225
- 로그아웃 후 로그인화면으로 이동하는 이동 메서드 변경
> [Fix/#225] 로그아웃 후 로그인화면으로 이동하는 이동 메서드 변경

- frontend/ios/Podfile.lock
- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/ios/Runner/AppDelegate.swift
- frontend/ios/Runner/Info.plist
- frontend/lib/screens/home_screen.dart
- frontend/macos/Flutter/GeneratedPluginRegistrant.swift
- frontend/pubspec.lock
- frontend/pubspec.yaml
#227
- 사용자일 때는 announcementLevel이 0일때도 저장되게 작성
- 관리자일 때는 announcementImportant가 true일 때 저장되게 작성
- 버전 수정
- Frontend -> 곰곰이 알리미
> [Fix/#227] 홈화면에서 필독 공지 학년 설정 고치기

- frontend/lib/screens/memberRecruit_screen.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
#228
- 중복 제거를 위해 toSet() 사용
- 버전 올림
> [feat : #228] 팀원 모집 파트에서 카테고리 중복 오류 처리

- frontend/lib/screens/changePW_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
#239
- 비밀번호 변경 페이지 상단바 색상 하얀색으로 변경
- 모집글 작성자 스택 보여주는 모달창 텍스트 수정 및 주석 수정
- 텍스트 버튼 스타일 styleForm 형식으로 변경
> [fix : #239] 비밀번호 변경 페이지에 상단바 색상 하얀색으로 변경하기

- frontend/lib/screens/recruitDetail_screen.dart
#242 
- url_launcher 패키지 사용해 실제로 url이 실행되도록 적용
- RichText 자체만으로는 클릭 이벤트를 지원하지 않아 GestureDetector로 감싸서 처리
> [fix : #242] 깃허브 링크 들어갈 수 있게 만들기

- frontend/lib/screens/setExperience_screen.dart
#244 
- LEADER, MEMBER 드롭다운 메뉴로 변경하여 선택하도록
- 드롭다운 메뉴 배경색 하얀색으로 변경
> [fix : #244] 프젝 경험 작성에서 LEADER, MEMBER를 드롭다운 메뉴로 변경하기

- frontend/lib/screens/memberRecruit_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
#251 
- 모집글 작성자 입장에서 신청자 반려하기 버튼 형식 추가
[ MemberRecruitPage ]
- 카테고리 선택 여부에 따라 보이는 팝업 메뉴 달라지도록 설정
> [Feat : #251] 반려하기 버튼 추가하기

- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/notificationList_screen.dart
- frontend/lib/screens/setExperience_screen.dart
- cateIndex 값에 따라 추출하는 코드를 따로 작성해서 분리
> [Fix/#256] 알림리스트에 팀원모집 알림이 안나오는 오류 수정
