- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/screens/memberRecruit_screen.dart
- frontend/pubspec.yaml
#29 
- 인원 수 버튼을 생성하는 위젯과 희망 분야 버튼을 생성하는 위젯 각각 _buildPeopleCountButton과 _buildFieldButton으로 처리
- 선택된 인원 수를 저장하는 상태 변수 selectedPeopleCount를 선언하고 선택된 희망 분야를 저장하는 상태 변수 selectedField 선언하여 상태 관리
- 제목 텍스트 제어하는 컨트롤러와 내용 텍스트 제어하는 컨트롤러 각각 설정
- ValueNotifier는 값이 변경될 때 리스너들에게 알릴 수 있는 간단한 클래스로, 주로 상태 관리에 사용
- 제목과 내용 작성 완료되면 작성 완료 버튼 활성화
https://github.com/Jeong-Reminder/reminder-frontend/assets/136067544/356e2e73-a552-4ffe-810e-5015b0af3c29
> [feat : #29] 팀원 모집글 작성 페이지 구현

- frontend/lib/screens/changePW_screen.dart
- frontend/lib/screens/home_screen.dart
#34
- TextFormField로 구현
- 새 비밀번호 입력 시 길이, 영문자, 툭수문자 유효성 검사
- 새 비밀번호 확인 입력 시 새 비밀번호와 동일한지 검사
- 유효성 검사가 완료될 시 다이얼로그 표시 및 이전 페이지로 이동이 가능하게 구현
TextFormField에 Sizedbox를 씌우지 않아야 에러메시지가 띄워질 때 TextFormField 높이 영향없이 띄울 수 있다.
> [Feat/#34] 비밀번호 변경 페이지 구현

- frontend/lib/screens/recruitDetail_screen.dart
#38 
- 글쓴 사람의 기술 스택 다이얼로그 표시할 수 있도록 _showAuthorStackDialog 함수 설정
- 반려 버튼 클릭 시 모집 인원이 1명씩 추가되는데 반려 버튼 클릭 시 모집 인원 추가 안 되고 사라지도록 수정
https://github.com/Jeong-Reminder/reminder-frontend/assets/136067544/444fc202-0241-4ae9-b5fc-9a7e956de1ab
> [feat : #38] 신청 팀장 정보 확인 페이지 구현

- frontend/ios/Podfile.lock
- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/ios/Runner/Info.plist
- frontend/lib/screens/profileSetting_screen.dart
#44
- imagepicker 패키지 사용
- Info.plist파일에서 카메라, 사진, 마이크 권한 코드를 추가해야 틩김 현상 오류 해결
- 프로필을 설정해야만 다음 페이지로 이동 가능하게 구현
- 설정을 안하고 이동할 시 "프로필을 설정하세요"라고 출력
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/05c99a7e-fcd9-484d-a7da-fdca41eb3a3d
> [Feat/#44] 프로필 설정하기 페이지 구현

- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/addMember_screen.dart
#77
- toggle_switch 패키지 사용
###관리자 회원가입 API 코드 구현
- Provider 패키지를 활용하여 Provider를 생성해 데이터 변화 상태 알림
-  회원 추가 model를 생성해 회원 정보 생성
https://github.com/Jeong-Reminder/reminder-frontend/assets/127868094/499becac-29f2-4b4a-920a-993545a680df
> [Feat(admin)/#77] 관리자 회원가입 API 연동

- frontend/ios/Podfile.lock
- frontend/lib/main.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/services/login_services.dart
- frontend/lib/widgets/account_widget.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
#86 
- AppLifecycleState 상태를 관찰하는 addObserver 매서드와 관찰을 중지하는 removeObserver 매서드를 활용하여 상태 인지되도록 구현
- 앱이 종료되거나 비활성화되는 경우의 AppLifecycleState 상태에 따라 logout API 호출되도록 구현
- 앱 종료 시  logout API  호출되도록 하는 logoutOnExit 함수 선언하여 관리되도록 구현
- AppLifecycleState 상태를 관찰하는 addObserver 매서드와 관찰을 중지하는 removeObserver 매서드를 활용하여 상태 인지되도록 구현
- 앱이 종료되거나 비활성화되는 경우의 AppLifecycleState 상태에 따라 logout API 호출되도록 구현
> [Feat/#86] 로그아웃 API 연동

- frontend/lib/models/profile_model.dart
- frontend/lib/providers/profile_provider.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/settingProFile1_screen.dart
- frontend/lib/screens/settingProfile_screen.dart
- frontend/lib/services/profile_service.dart
#89
- profile 모델 생성
- githubUrl과 hopeJob은 settingprofile 페이지로 전달
- 선택한 field와 tool 리스트를 map 메소드와 join 메소드를 활용하여 하나의 문자열로 변환
- 상태 관리할 profile을 위해 생성
- techStack.isNotEmpty를 하기 전에 null인지 아닌지 확인해야 함
- 프로필 생성 시 ProfileProvider 호출
> [Feat/#89] 프로필 생성 API 연동

- frontend/lib/main.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/settingProFile1_screen.dart
- frontend/lib/services/login_services.dart
#95
[ 로그인 시 적용 ]
- techStack 값이 null이거나 값이 비어있는 경우 SettingProfile1Page로 이동되도록 구현
- memberExperience 값이 null이거나 값이 비어있는 경우 SettingProfile2Page로 이동되도록 구현
- techStack, memberExperiences 값이 둘 다 채워진 경우 HomePage로 이동되도록 구현
[ 앱 종료 시 ]
- userRole 값을 getString으로 가져옴
- 앱 종료 후 다시 접속할 때 가져온 userRole 값에 따라 처음 보이는 화면 다르게 설정
- 토큰 재발급 API 호출되어 성공 되었을 때도 마찬가지로 적용
- 용량이 너무 커 사진 캡쳐로 대체하겠습니다
> [Fix/#95] 로그인 관련 페이지 이동 코드 수정

- frontend/lib/providers/projectExperience_provider.dart
- frontend/lib/services/projectExperience_service.dart
#97 
- ProjectExperience 모델 사용하여 List 형식으로 나열되도록 구현
- toJson 메서드를 호출하여 해당 객체를 JSON으로 변환하고 toList 형식으로 변환하여 받음
- 프로젝트 경험 여러개 추가 시 ProjectExperienceProvider 호출
- notifyListeners 매서드 사용하여 상태 변경 알림 적용
> [feat : # 97] 프로젝트 경험 여러개 추가 API 연동

- frontend/lib/main.dart
- frontend/lib/providers/projectExperience_provider.dart
- frontend/lib/screens/experience_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/screens/settingProfile2_screen.dart
- frontend/lib/services/login_services.dart
- frontend/lib/services/projectExperience_service.dart
- frontend/lib/widgets/profile_widget.dart
#99 
[로그인 후 MyUserPage 프로필 이름과 재적상태 일치되도록 구현]
[LoginAPI_Service]
- 로그인할 때 name, status SharedPreferences에 저장하는 코드 추가 구현
- 저장된 name, status를 loadCredentials 메서드로 가져오기 위해 getString 방식 적용
[MyUserPage]
- 이름, 재적상태를 로드하는 메서드 _loadStudentId 선언하여 이름과 재적상태 관리
- 이름과 재적상태가 없는 경우 기본 값을 빈 문자열로 설정
[Profile]
- name, status 매개변수 추가
- showSubTitle이 true인 경우 status를 화면에 표시되도록 구현
[ExperiencePage]
- 로그인 후 해당 학생 이름으로 상태 변경되도록 구현
[main]
ExperiencePage에 파라미터로 name 추가
https://github.com/user-attachments/assets/da16cef6-1bb4-4178-a3c8-3e76753f20db
> [Feat/#99] 내 프로젝트 경험 조회 API 연동

- frontend/lib/models/projectExperience_model.dart
- frontend/lib/providers/projectExperience_provider.dart
- frontend/lib/screens/experience_screen.dart
- frontend/lib/screens/myOwnerPage_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/login_services.dart
- frontend/lib/services/projectExperience_service.dart
#100 
[Login_Service]
-  memberExperience 배열에서 id 값 추출하여 저장
[ProjectExperienceService]
- memberExperience 배열에서 추출한 id 값 가져옴
- 가져온 id 값을 experienceIds 변수의 저장
- projectExperience 객체에서 id를 추출
[Model]
- id 필드와 memberId 필드 추가 적용
- JSON 데이터에서 id와 memberId 추출
[Provider]
- projectExperiences 리스트에서 updatedProjectExperience와 동일한 id를 가진 항목의 인덱스를 찾도록 변경
[RecruitDetailPage]
- ExperiencePage 이동 시 필요한 파라미터 추가
[ExperiencePage]
- Provider를 사용하여 경험 데이터를 업데이트 및 즉시 반영되도록 구현
[MyOwnerPage]
- Profile 누락된 정보 추가
> [feat : #100] 프로젝트 경험 수정 API 연동

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/all/providers/models/board_model.dart
- frontend/lib/main.dart
- frontend/lib/screens/board_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/services/login_services.dart
- frontend/lib/widgets/boardAppbar_widget.dart
- frontend/lib/widgets/board_widget.dart
#112
- 공지 전체를 볼 수 있는 페이지를 따로 생성
- 상단바를 공통 위젯으로 분리
- 초기값에 전체 조회 API 호출(addPostFrameCallback 사용)
- board 위젯을 만들어 get 메서드로 boardList를 불러 board 위젯으로 전달해 UI 구현
- 로그인 정보의 학년 값대로 해당 공지글 보여주도록 설정
- 관리자나 학생에 따라 드롭메뉴 보여지도록 구현
> [Feat/#112] 게시글 전체 조회 API 연동

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/corSeaBoard_screen.dart
- frontend/lib/screens/gradeBoard_screen.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/services/login_services.dart
- frontend/lib/services/profile_service.dart
- frontend/lib/widgets/board_widget.dart
#122
- board 위젯에 onBoardSelected 파라미터를 추가해 선택된 게시글을 받은 후 선택된 게시글을 저장할 변수에 저장
- onLongPressed로 isHidDel 상태값을 설정해 true일 경우 bottomNavigationBar 생기게 구현
- 삭제 버튼 내에 삭제 API 호출 뒤 바로 업데이트된 boardList를 보여주기 위해 조회도 호출
> [Feat/#122] 게시글 삭제 API 연동

- frontend/lib/all/providers/announcement_provider.dart
- frontend/lib/main.dart
- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/corSeaBoard_screen.dart
- frontend/lib/screens/gradeBoard_screen.dart
- frontend/lib/screens/hiddenList_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/widgets/board_widget.dart
#30
- 숨김 관리 페이지로 이동할 때 category 값을 전달해 category값에 따라 이동하는 페이지가 다르게 작성
- 숨김과 동일하게 board_widget에서 선택한 게시글을 받아서 API 메서드 호출
> [Feat/#130] 게시글 보이기 API 연동

- frontend/lib/providers/teamApply_provider.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/teamApply_service.dart
#154
- 현재 사용자가 댓글 작성자인 경우에만 팝업 메뉴를 보여주는 상태에서 삭제 popupItem 클릭 시 삭제되도록 구현
- 신청글 삭제하는 함수 _deleteContent 선언하여 관리
> [feat :#154] 팀원 신청글 삭제 API 연동

- frontend/lib/models/vote_model.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/screens/write_screen.dart
- frontend/lib/widgets/vote_widget.dart
#149
- 엑세스 토큰 받은 후 헤더에 작성 및 응답이 비어있기 때문에 200이거나 204일 경우 투표 종료 성공이 콘솔에 출력되게 작성
- 종료시간을 투표 바로 옆에 놓고 종료 버튼을 우측 상단에 배치하는데 어드민만 볼 수 있도록 작성
- 투표 모델에 voteEnded 추가 및 endDateTime로 이름 수정
- 투표 종료 API 메서드에 투표 종료 성공 시 투표 조회 호출 코드 추가
- 투표 종료일 경우 더보기 버튼과 항목 추가 버튼이 안보이게, 투표 버튼에서 투표 종료 버튼으로 설정
> [Feat/#149] 투표 종료 API 연동

- frontend/lib/models/vote_model.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/screens/write_screen.dart
- frontend/lib/widgets/vote_widget.dart
#150
- repetition에 따라 선택한 항목을 담는 변수타입을 다르게 설정
- 항목을 클릭했을 때 해당 아이디값을 추가하고 다시 클릭했을 때 해당 아이디값이 있으면 삭제
- hasVoted가 true이면 인원 수 표시와 재투표하기 버튼으로 변환
- 항목 입력 칸 열고 닫기 여부와 항목 입력 컨트롤러 변수를 선언
- 컨트롤러가 비어있지 않을때 항목 추가, 조회 api 호출 후 항목 입력 칸을 닫기 위해 isOpened를 false로  설정
- 다른 내용을 작성하기 위해 컨트롤러 클리어
- 관리자 혹은 투표 완료일 경우 항목 추가 클릭 기능 상실
- 재투표 여부를 선언해 재투표하기 버튼을 눌렀을 때 재투표 여부를 true로 변환해 재투표 API를 호출할 수 있도록 설정
- vote.hasVoted를 false로 변환해 선택 시 아이콘(원모양) 보이게 하고
- 투표 api 호출하는부분에서 재투표 api 호출 코드를 작성할 수 있도록 작성
- 나중에 다시 재투표할 수 있도록 설정
- 항목추가와 투표하기 버튼은 사용자만 볼 수 있게 구현
- 관리자는 해당 투표 항목 인원은 무조건 볼 수 있게 구현
- 투표 삭제할 때 경고 다이얼로그를 띄워 삭제하도록 설정 후 게시글 조회를 해 UI 바로 업데이트되게 구현
> [Feat/#150] 투표 관련 API 연동

- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/screens/memberRecruit_screen.dart
#167
- 개별 삭제라는 팝업 메뉴 생성
- 클릭 시 만들어진 카테고리 이름의 팝업 메뉴 생성
recruitment 카테고리별 삭재 API 연동
- 전체 혹은 개별 삭제 일 경우 api 호출을 다르게 적용
- 파라미터에 []를 덮어서 선택적으로 값을 주도록 작성
- 파라미터에 [ ]를 덮어서 선언
> [Feat/#167] recruitment 카테고리별 삭제

- frontend/lib/main.dart
- frontend/lib/providers/makeTeam_provider.dart
- frontend/lib/providers/teamApply_provider.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/makeTeam_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/makeTeam_service.dart
- frontend/lib/services/teamApply_service.dart
#164 
- ['data'] 값을 recruitList 변수에 담아서 적용되도록 구현
- 승인 버튼 클릭하면 memberRole에 따라 명단에 자동으로 추가되도록 구현
- 명단에 추가된 member 2x2 형식으로 나열되도록 구현
- 팀 생성 service 작성
- 팀 생성 provider 작성
> [Feat/#164] 팀 생성 API 연동

- frontend/lib/admin/providers/admin_provider.dart
- frontend/lib/admin/screens/contestTeamList_screen.dart
- frontend/lib/admin/screens/dashboard_screen.dart
#174
- 팀 전체 조회 API를 contestTeamList 파일에 initState에서 작성
- AdminProvider에서 저장한 teamList를 가져와 저장
- 팝업 메뉴를 통해 선택한 해당 카테고리의 팀 정보를 확인할 수 있도록 구현
- 검색어를 통해 하나만 포함되도 팀명이나 경진대회의 팀정보를 확인할 수 있도록 구현
> [Feat/#174] 팀 전체 조회 API 연동

- frontend/lib/screens/contestBoard_screen.dart
- frontend/lib/screens/corSeaBoard_screen.dart
- frontend/lib/screens/gradeBoard_screen.dart
- frontend/lib/screens/myOwnerPage_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
#181
- 월과 일을 출력해 학기별로 분류하고 중복되는 값들은 제거한 후 '년 학기'로 출력
- onSelectedItemChanged 속성에서 게시글 생성시간을 연도-학기로 추출해 semesterList와 동일한 요소가 있는지 확인
- 동일한게 확인되면 selectedBoardList에 저장
- 영어로 된 카테고리를 한글로 변환하는 함수 구현
- CupertinoPicker에 초기 값 지정
- ListTile의 onTap 속성에서 내비게이터 위젯을 사용해서 id로 전달과 동시에 상세 페이지 이동 구현
- 현재 시간을 구해 게시글 생성시간의 차이를 구해 2년 이상이면 게시글 삭제 호출 후 게시글 조회
- 현재시간이 1월 1일인지 확인
- 메서드를 전체, 학년, 경진대회, 계절, 기업 공지글에 다 적용
DateTime
> [Feat/#181] 작성 내역 구현

- frontend/lib/providers/projectExperience_provider.dart
- frontend/lib/screens/experience_screen.dart
- frontend/lib/screens/recruitDetail_screen.dart
- frontend/lib/services/projectExperience_service.dart
#189 
- recruitList에서 memberId가 일치하는 멤버 적용해서 이름 UI에 표시
- memberId 추출해서 해당 멤버의 프로젝트 경험 조회할 수 있도록
- service 작성
- provider 작성
https://github.com/user-attachments/assets/d554e4f1-8a83-4623-92e0-a92b09c9c7d4
> [feat : #189] 다른 사람 프로젝트 경험 조회 api 연동

- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/hiddenList_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/widgets/board_widget.dart
#187
- 게시글 목록 페이지에서 길게 눌러서 숨김 삭제 기능에서 통일성을 위해 상세 페이지의 팝업 메뉴에서 구현할 수 있게 변경
- 공지 카테고리에 맞게 이전페이지로 이동하는 함수를 생성
- 숨김 페이지에서 숨김 해제 후 새로고침할 때 숨김 해제 버튼 없애기 위해 isHidDel를 false로 설정
- 제목, 내용 각각 20, 30자 이상일 때 ... 처리
> [Fix/#187] 게시글 숨김/삭제 위치 변경

- frontend/lib/main.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/myOwnerPage_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/widgets/board_widget.dart
#186
- FutureBuilder를 사용해서 비동기로 공지를 띄움
- 어드민일 경우 important가 true일 때만 필터링
- 유저일 경우 멤버 학년과 공지 학년이 동일한 것까지 포함해서 필터링
- 작성된 공지가 없을 경우 container() 위젯을 통해 필독 공지 자리 공간을 제거
- category에 HOME을 넣고 전달해 이전페이지로 이동할 수 있게 구현
- richText 위젯을 사용해서 글 제목이나 내용이 컨테이너 크기를 초과하면 ellipsis 혹은 clip 속성 사용
- 프로필페이지에서 계정 위젯을 화면 화단에 고정 
RichText()
> [Feat/#186] 홈화면에서 공지 띄우기

- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/setExperience_screen.dart
#208
- 로그인에서 학번, 비번, 토큰을 저장한 후 경험 생성 후 로그인 호출
- 로그인 파라미터에 저장했던 학번, 비번, 토큰을 꺼내서 집어넣음
https://github.com/user-attachments/assets/d343b2fc-4a2d-4d54-8532-8733fb7fe329
> [Fix/#208] 회원 새 등록 시 다른 사람의 프로필이 띄워지는 오류 수정

- frontend/lib/admin/screens/userInfo_screen.dart
- frontend/lib/providers/announcement_provider.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/downloadImage_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/myOwnerPage_screen.dart
- frontend/lib/screens/myUserPage_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
- frontend/lib/screens/update_screen.dart
- frontend/lib/screens/write_screen.dart
- frontend/lib/widgets/board_widget.dart
- frontend/lib/widgets/vote_widget.dart
#212
- sort 메서드를 사용해서 두 개의 공지사항 시간을 비교하여 순서를 결정
- compareTo 메서드를 이용해서 두 날짜를 비교해 반환값에 따라 순서를 결정
- 양수이면, 순서를 변경하고 음수이면, 순서를 변경하지 않음
- Hero 위젯을 사용하여 검은 바탕의 이미지 전체를 볼 수 있는 페이지로 이동
- entry.key와 pickedImages.length를 전달해 몇번째 이미지인지 상단바에 표시
- 혹시 모를 이미지 다운을 위해 url과 파일 이름을 전달한 후 파일 다운 api를 작성
- 이름, 학번, 학년, 학정상태에 숫자를 부여해 숫자마다 if문을 적용
- 정렬방식은 compareTo 메서드를 사용해서 isAscending 값에 따라 내림⋅오름 차순 설정
- 검색하지 않았을 경우에는 전체 리스트로, 검색했을 경우에는 검색 결과 리스트로 정렬 기능 구현
- 전체 너비의 절반으로 수정
https://github.com/user-attachments/assets/5f1bdb4b-c4d3-435e-b166-cb4abb2fb66e
https://github.com/user-attachments/assets/6cacbf00-c0e1-47eb-8998-4b55a6a40b3a
> [Feat/#212] 기능 구현

- frontend/lib/screens/recruitDetail_screen.dart
#237 
- 관리자의 경우 승인 처리를 버튼 형식이 아니라 팝업 메뉴 형식으로 변경
- 모달창 색상 구조 변경
- 모집글 작성자 이름 클릭 시
- 댓글 작성자 이름 클릭 시
- 승인하기 팝업 메뉴 클릭 시
- 팝업 메뉴 배경 색상 0xFFEFF0F2로 동일하게 적용
> [Fix/#237] ‘승인하기’ 버튼 디자인 수정하기

- frontend/lib/screens/editField_screen.dart
- frontend/lib/screens/editTool_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/userInfo_screen.dart
- frontend/lib/services/login_services.dart
#240
- 프로필 조회는 Text 위젯을 사용해 userPage에서 받은 profile로 구현
- 프로필 수정 모달창에서 controller로 볼 수 있게 해놨고 수정할 때도 값들을 controller.text로 값을 보냄
- 저장 버튼 시 userInfo 페이지에서 바로 업뎃시키기 위해 모달창을 Map으로 반환타입을 지정해
결과값을 widget.profile에 저장
- 취소하고 모달창에 수정된게 보이는 오류가 발생해 initState에 값들과 컨트롤러를 저장을 제거하고
컨트롤러는 모달창 함수에 초기화
- url_launcher 패키지를 사용하고 파란 색상으로 변경
- 홈페이지에서 마이페이지로 이동할 때 3초 후 다이얼로그 닫는 코드 제거
- 로그인 페이지에서 커서, 포커스 색상을 앱 대표 색상으로 변경
> [Fix/#240] 프로필 수정 UI 변경하기

- frontend/lib/screens/setExperience_screen.dart
#252
- 경험 작성에 쓰일 컨트롤러와 문자열 변수를 리스트로 생성
- 경험 추가하기 버튼은 통해 add 함수 실행과 formatLength 1 추가
- formatLength 길이로 인해 경험 작성 양식을 ListView.separted를 통해 생성
- 각각 리스트 0번째 값이 비어있지 않으면 경험 추가하기 버튼을 표시, 그렇지 않으면 없음을 표시
- 프로젝트명 컨트롤러 리스트 개수에 따라 for문을 돌려 경험 정보들을 저장 후 newExperiecs 리스트에 추가
- 텍스트폼필드에 포커스 색상과 커서 색상을 대표 색상으로 변경
- 경험 조회 화면에서 올 경우에만 경험 추가하기 버튼이 보이게 구현
> [Feat/#252] 경험 여러 개 추가하기

- frontend/lib/main.dart
- frontend/lib/providers/vote_provider.dart
- frontend/lib/screens/boardDetail_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/screens/login_screen.dart
- frontend/lib/screens/totalBoard_screen.dart
#250
- 전체 게시글의 생성 시간과 달력의 날짜와 비교해 동일한 게시글을 selectedBoardList에 저장(추가)
- selectedBoardList가 있으면 showModalBottomSheet 위젯을 통해 투표가 있는 게시글만 투표 표시
- 달력에서 색상 스타일링 구현
- 투표 전체 조회 API 구현
- 투표 전체 조회 리스트(voteList) 생성
- voteList와 boardList를 차례로 for문을 돌아 게시글 아이디와 투표의 게시글 아이디가 동일하면 시작시간과 종료시간을 구함
- 시작일 이후와 종료일 이전이면 events에 추가해 반환
- 게시글아이디와 투표의 게시글 아이디가 동일하면 시작과 종료시간을 생성해 년-월-일이 사이에 있으면 달력에 일정 넣기
https://github.com/user-attachments/assets/26141b2a-603d-4a4b-b3d3-1519632144af
TableCalendar의 기능들
> [Feat/#250] 달력에 투표 일정 넣기
